## Provides autodetected defaults, for vanilla Docker environments,
## please see datadog.yaml.example for all supported options

apm_config:
  apm_non_local_traffic: true

  # 特定のURLを無視する
  ## filter_tagsは文字列の完全一致で比較する
  ## https://docs.datadoghq.com/ja/tracing/guide/ignoring_apm_resources/
  filter_tags:
    reject: [
      # ヘルスチェック
      "http.route:/",
    ]
  
  # 特定のリソースを無視する
  ## goのregexpで正規表現を評価する
  ## https://docs.datadoghq.com/ja/tracing/guide/ignoring_apm_resources/
  ignore_resources: [
    "Laravel\\Telescope\\.*",
    ".*/telescope/.*"
  ]

# Use java container support
jmx_use_container_support: true
